### ISSUE TITLE
rekit-studio@next 启动报错

### ISSUE THREAD

**Issue by dingyiming** [rekit/rekit-studio#1]
安装了  rekit-studio@next ，使用就报错了

![image](https://user-images.githubusercontent.com/12537013/56374981-f504cf80-6236-11e9-8f2a-b3040a88c502.png)

**Comment by OrionPax123** [comment]
同样是此问题

**Comment by supnate** [comment]
可能是 windows 系统上有问题，回头找 windows 机器重现下。

**Comment by zzz6519003** [comment]
dmg download?

**Comment by supnate** [comment]
Windows issue should have been fixed, please download the latest beta version.
