### ISSUE TITLE
Overview diagram is not correctly positioned

### ISSUE THREAD

**Issue by dkocich** [rekit/rekit-studio#16]
when I open a new empty project, I can't see the diagram completely and I can't find any option how to move in its view box (mouse drag with clicked right mouse button; holding a keyboard button and mouse drag at the same time, etc.).

![image](https://user-images.githubusercontent.com/6165660/92725443-7436fe00-f36c-11ea-921b-ee1e93accbda.png)

I am on Windows, Chrome browser; I have 100% scale of system resolution (different scale usually caused me this type of problems).

**Comment by supnate** [comment]
Thanks for reporting, it's a known issue since some version of Chrome update. Will address it soon. However, the desktop on Mac doesn't have the issue.
